import ABOUT from './about.svg';
import EXPERIENCE from './experience.svg';
import STUDENT from './student.svg';
import VISSION from './vission.svg';
import GOALS from './goals.svg';
import MISSION from './mission.svg';
import OURVALUES from './ourvalues.svg';
import OCEAN from './ocean_logo.svg';
import OA from './oa.svg';
export{ABOUT,EXPERIENCE,STUDENT,VISSION,GOALS,MISSION,OURVALUES,OCEAN,OA};